$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline

experiment_name: pipeline_51

jobs:

  data_prep:
    command: python data_prep.py

  train:
    command: python train_pipeline.py

  evaluate:
    command: python evaluate.py